# Generated by Django 5.1.5 on 2025-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_subject_title_remove_subject_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='_content',
        ),
        migrations.AddField(
            model_name='option',
            name='content',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='NULL'),
        ),
    ]
