# Generated by Django 5.1.5 on 2025-01-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_option__content_remove_question__content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correct_for_questions', to='api.option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
