import { Question } from "@/types/types";

export const questionBank: Question[] = [
  {
    id: "1",
    text: "Which of the following is a key principle of Lean Manufacturing?",
    choices: [
      { id: "a", text: "Maximizing inventory to meet demand" },
      { id: "b", text: "Eliminating waste in all forms" },
      { id: "c", text: "Increasing production batch sizes" },
      { id: "d", text: "Focusing on individual worker efficiency over system flow" },
    ],
    answer: "b",
    explanation: "Lean Manufacturing focuses on the elimination of 'muda' or waste in all its forms to improve efficiency and value.",
  },
  {
    id: "2",
    text: "In project management, what does PERT stand for?",
    choices: [
      { id: "a", text: "Project Evaluation and Resource Tracking" },
      { id: "b", text: "Program Evaluation and Review Technique" },
      { id: "c", text: "Process Efficiency and Resource Technology" },
      { id: "d", text: "Project Execution and Reporting Tool" },
    ],
    answer: "b",
    explanation: "PERT (Program Evaluation and Review Technique) is a statistical tool used in project management to analyze and represent the tasks involved in completing a given project.",
  },
  {
    id: "3",
    text: "What is the primary purpose of a Pareto Chart in quality control?",
    choices: [
      { id: "a", text: "To show the trend of a process over time" },
      { id: "b", text: "To identify the vital few causes of problems" },
      { id: "c", text: "To determine the correlation between two variables" },
      { id: "d", text: "To display the distribution of data" },
    ],
    answer: "b",
    explanation: "A Pareto Chart is a type of chart that contains both bars and a line graph, where individual values are represented in descending order by bars, and the cumulative total is represented by the line. It is used to identify the most significant factors in a set of data.",
  },
  {
    id: "4",
    text: "The '5S' methodology in workplace organization stands for:",
    choices: [
      { id: "a", text: "Sort, Set in order, Shine, Standardize, Sustain" },
      { id: "b", text: "Safety, Speed, a, Standardize, Service" },
      { id: "c", text: "Sort, a, Shine, Schedule, Sustain" },
      { id: "d", text: "Streamline, Set in order, Shine, Standardize, Support" },
    ],
    answer: "a",
    explanation: "The 5S methodology is a workplace organization method that uses a list of five Japanese words: seiri (sort), seiton (set in order), seiso (shine), seiketsu (standardize), and shitsuke (sustain).",
  },
  {
    id: "5",
    text: "In queuing theory, what does the term 'M/M/1' represent?",
    choices: [
      { id: "a", text: "A single-server queuing system with Markovian arrivals and service times" },
      { id: "b", text: "A multi-server queuing system with deterministic arrivals" },
      { id: "c", text: "A queuing system with one server and multiple queues" },
      { id: "d", text: "A system with multiple servers and a single queue" },
    ],
    answer: "a",
    explanation: "In Kendall's notation, M/M/1 represents a single-server queuing system where arrivals follow a Poisson process (Markovian) and service times follow an exponential distribution (Markovian).",
  },
  {
    id: "6",
    text: "What is the main goal of Six Sigma?",
    choices: [
      { id: "a", text: "To reduce process variation and defects" },
      { id: "b", text: "To increase the number of product features" },
      { id: "c", text: "To implement a new technology" },
      { id: "d", text: "To reduce the workforce" },
    ],
    answer: "a",
    explanation: "Six Sigma is a set of techniques and tools for process improvement, seeking to improve the quality of the output of a process by identifying and removing the causes of defects and minimizing variability.",
  },
  {
    id: "7",
    text: "Which of these is a primary tool for ergonomic analysis in the workplace?",
    choices: [
      { id: "a", text: "Gantt Chart" },
      { id: "b", text: "Rapid Upper Limb Assessment (RULA)" },
      { id: "c", text: "Fishbone Diagram" },
      { id: "d", text: "Control Chart" },
    ],
    answer: "b",
    explanation: "RULA is a survey method developed for use in ergonomics investigations of workplaces where work-related upper limb disorders are reported.",
  },
  {
    id: "8",
    text: "What does EOQ stand for in inventory management?",
    choices: [
      { id: "a", text: "Estimated Order Quantity" },
      { id: "b", text: "Economic Order Quantity" },
      { id: "c", text: "Equal Order Quantity" },
      { id: "d", text: "Effective Order Quantity" },
    ],
    answer: "b",
    explanation: "Economic Order Quantity (EOQ) is the order quantity that minimizes the total holding costs and ordering costs in inventory management.",
  },
  {
    id: "9",
    text: "The DMAIC cycle in Six Sigma stands for:",
    choices: [
      { id: "a", text: "Define, Measure, Analyze, Improve, Control" },
      { id: "b", text: "Design, Manufacture, Assemble, Install, Check" },
      { id: "c", text: "Define, Manage, Analyze, Implement, Control" },
      { id: "d", text: "Design, Measure, Analyze, Innovate, Control" },
    ],
    answer: "a",
    explanation: "DMAIC (Define, Measure, Analyze, Improve, Control) is a data-driven improvement cycle used for improving, optimizing and stabilizing business processes.",
  },
  {
    id: "10",
    text: "What type of layout is best suited for producing a high volume of a single product?",
    choices: [
      { id: "a", text: "Process Layout" },
      { id: "b", text: "Fixed-Position Layout" },
      { id: "c", text: "Product Layout" },
      { id: "d", text: "Cellular Layout" },
    ],
    answer: "c",
    explanation: "A Product Layout (or line layout) is used to achieve a smooth and rapid flow of large quantities of goods or customers through a system.",
  },
  {
    id: "11",
    text: "What is the purpose of a Failure Modes and Effects Analysis (FMEA)?",
    choices: [
      { id: "a", text: "To analyze the financial performance of a project" },
      { id: "b", text: "To identify potential failures in a design or process" },
      { id: "c", text: "To schedule maintenance activities" },
      { id: "d", text: "To determine the root cause of a single defect" },
    ],
    answer: "b",
    explanation: "FMEA is a step-by-step approach for identifying all possible failures in a design, a manufacturing or assembly process, or a product or service.",
  },
  {
    id: "12",
    text: "In a time study, what is 'allowance'?",
    choices: [
      { id: "a", text: "The time allowed for a worker to rest" },
      { id: "b", text: "The extra time added to the normal time to account for personal needs, fatigue, and delays" },
      { id: "c", text: "The time it takes to complete a task without any interruptions" },
      { id: "d", text: "The time a worker is allowed to be late" },
    ],
    answer: "b",
    explanation: "Allowances in time study are the extra time added to the normal time to provide for personal needs, fatigue, and unavoidable delays.",
  },
  {
    id: "13",
    text: "What is the primary goal of Supply Chain Management?",
    choices: [
      { id: "a", text: "To minimize transportation costs" },
      { id: "b", text: "To manage the flow of goods and services from raw materials to the end consumer" },
      { id: "c", text: "To increase the number of suppliers" },
      { id: "d", text: "To automate the warehousing process" },
    ],
    answer: "b",
    explanation: "Supply Chain Management is the management of the flow of goods and services and includes all processes that transform raw materials into final products.",
  },
  {
    id: "14",
    text: "Which of the following is an example of a stochastic process?",
    choices: [
      { id: "a", text: "The movement of a clock's hands" },
      { id: "b", text: "The arrival of customers at a store" },
      { id: "c", text: "The calculation of a loan's interest" },
      { id: "d", text: "A chemical reaction with known inputs" },
    ],
    answer: "b",
    explanation: "A stochastic process is a mathematical object usually defined as a family of random variables. It is used to model systems that evolve randomly over time, such as customer arrivals.",
  },
  {
    id: "15",
    text: "What does 'Kaizen' mean in the context of continuous improvement?",
    choices: [
      { id: "a", text: "A one-time major improvement" },
      { id: "b", text: "A philosophy of continuous, incremental improvement" },
      { id: "c", text: "A quality control tool" },
      { id: "d", text: "A method for statistical analysis" },
    ],
    answer: "b",
    explanation: "Kaizen is a Japanese term meaning 'change for the better' or 'continuous improvement.' It is a business philosophy of continuously improving operations and involving all employees.",
  },
  {
    id: "16",
    text: "Which of the following is a key component of a Just-In-Time (JIT) inventory system?",
    choices: [
      { id: "a", text: "Large safety stocks" },
      { id: "b", text: "Production based on long-term forecasts" },
      { id: "c", text: "Small, frequent deliveries of materials" },
      { id: "d", text: "A focus on economies of scale in purchasing" },
    ],
    answer: "c",
    explanation: "JIT is an inventory strategy that aims to receive goods from suppliers only as they are needed in the production process, which reduces inventory holding costs.",
  },
  {
    id: "17",
    text: "In facilities planning, what is a 'from-to' chart used for?",
    choices: [
      { id: "a", text: "To show the flow of materials between departments" },
      { id: "b", text: "To track the progress of a project over time" },
      { id: "c", text: "To analyze the financial costs of a facility" },
      { id: "d", text: "To schedule employee shifts" },
    ],
    answer: "a",
    explanation: "A from-to chart is a table that shows the flow of materials or people between different locations or departments, which is useful for designing efficient layouts.",
  },
  {
    id: "18",
    text: "What is the primary purpose of a control chart?",
    choices: [
      { id: "a", text: "To determine if a process is in a state of statistical control" },
      { id: "b", text: "To identify the root cause of a problem" },
      { id: "c", text: "To display the relationship between two variables" },
      { id: "d", text: "To forecast future performance" },
    ],
    answer: "a",
    explanation: "Control charts are used to determine whether or not a manufacturing or business process is in a state of statistical control.",
  },
  {
    id: "19",
    text: "Which of the following is NOT one of the seven basic tools of quality?",
    choices: [
      { id: "a", text: "Histogram" },
      { id: "b", text: "Check Sheet" },
      { id: "c", text: "Gantt Chart" },
      { id: "d", text: "Cause-and-Effect Diagram" },
    ],
    answer: "c",
    explanation: "The seven basic tools of quality are: Cause-and-effect diagram, check sheet, control chart, histogram, Pareto chart, scatter diagram, and stratification. A Gantt chart is a project management tool.",
  },
  {
    id: "20",
    text: "What is the 'bottleneck' in a production process?",
    choices: [
      { id: "a", text: "The fastest part of the process" },
      { id: "b", text: "The most expensive part of the process" },
      { id: "c", text: "The part of the process with the lowest capacity" },
      { id: "d", text: "The part of the process with the highest quality" },
    ],
    answer: "c",
    explanation: "A bottleneck is a point of congestion in a production system (such as an assembly line or a computer network) that occurs when workloads arrive too quickly for the production process to handle.",
  }
]; 